sudo: required
language: node_js
node_js:
  - "7"
branches:
  only:
    - master
install:
  - npm install -g @angular/cli
  - npm install -g typings
  - npm install
script:
  - npm run build
  - zip -r website.zip dist
after_script:
  - chmod 777 netlify.sh
  - ./netlify.sh