sudo: false
language: node_js
node_js:
  - 7
branches:
  only:
    - master
install:
  - npm install -g @angular/cli
  - npm install -g typings
  - npm install
script:
  - npm run build
  - zip -r website.zip dist
after_script:
  - curl -H "Content-Type: application/zip" -H "Authorization: Bearer $NETLIFY" --data-binary "@website.zip" https://api.netlify.com/api/v1/sites/michaelsolati-com/deploys
  - exit 0